import NavBar from "./component/NavBar";
import AuthContext from "./context/AuthContext";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";

export const metadata = {
	title: "OpenTable",
	description: "Generated by me",
	image: "./favicon.ico",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<main className="bg-gray-100 min-h-screen w-screen">
					<AuthContext>
						<main className="max-w-screen-2xl m-auto bg-white">
							<NavBar />
							{children}
						</main>
					</AuthContext>
				</main>
			</body>
		</html>
	);
}
